---
- name: Install aptitude using apt
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest

- name: start and enable docker
  service:
    name: docker
    enabled: yes
    state: started  


- name: Install Docker Module for Python
  pip:
    name: docker

- name: Log into DockerHub
  docker_login:
    username: "{{ hub_username}}"
    password: "{{ hub_password }}"

- name: Copy docker file and run.py file
  copy:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
  with_items:
    - Dockerfile
    - run.py  
    
- name: Build an image and push it to a private repo
  docker_image:
    path: /tmp
    name: "{{ hub_registry }}"
    tag: v1
    push: yes

- name: Log out of DockerHub
  docker_login:
    state: absent
    username: "{{ hub_username}}"
